CREATE 	TABLE IF NOT EXISTS TIPO_BANCO(
	ID_TIPO BIGINT not null,
	NOMBRE_TIPO VARCHAR(25) not null,
	PRIMARY KEY (ID_TIPO)
);

CREATE TABLE IF NOT EXISTS BANCO(
	ID_BANCO BIGINT auto_increment not null,
	NOMBRE VARCHAR(50) not null,
	TIPO_BANCO BIGINT not null,
	PRIMARY KEY (ID_BANCO),
	foreign key (TIPO_BANCO) references TIPO_BANCO(ID_TIPO)
);

CREATE TABLE IF NOT EXISTS SUCURSALES(
	ID_SUCURSAL BIGINT auto_increment not null,
	NOMBRE_SUC VARCHAR(15) not null,
	ID_BANCO BIGINT not null,
	PRIMARY KEY (ID_SUCURSAL),
	foreign key (ID_BANCO) references BANCO(ID_BANCO)
);


INSERT INTO TIPO_BANCO VALUES(1,'COMERCIAL');
INSERT INTO TIPO_BANCO VALUES(2,'HIPOTECARIO');
INSERT INTO TIPO_BANCO VALUES(3,'ESTATAL');

INSERT INTO BANCO(NOMBRE,TIPO_BANCO)VALUES('GALICIA',1);
INSERT INTO BANCO(NOMBRE,TIPO_BANCO)VALUES('SANTANDER',1);
INSERT INTO BANCO(NOMBRE,TIPO_BANCO)VALUES('COMAFI',1);
INSERT INTO BANCO(NOMBRE,TIPO_BANCO)VALUES('HIPOTECARIO',2);
INSERT INTO BANCO(NOMBRE,TIPO_BANCO)VALUES('NACION',3);
INSERT INTO BANCO(NOMBRE,TIPO_BANCO)VALUES('PROVINCIA',3);

INSERT INTO SUCURSALES(NOMBRE_SUC,ID_BANCO)VALUES('Devoto',3);
INSERT INTO SUCURSALES(NOMBRE_SUC,ID_BANCO)VALUES('Palermo',1);
INSERT INTO SUCURSALES(NOMBRE_SUC,ID_BANCO)VALUES('Villa Crespo',2);

COMMIT;
